version: '3'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - fitness-tracker-volume:/workspaces
      # - node_modules:/workspace/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - NODE_ENV=development
      - PORT=3000
    entrypoint: [ "tail", "-f", "/dev/null" ]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongodb:27017/

volumes:
  fitness-tracker-volume:
