@baseUrl = http://localhost:3000

# @name register
POST {{baseUrl}}/auth/register 
content-type: application/json

{
    "username": "testitest",
    "email": "test@test.de",
    "password": "test1234"
}

###

// @name login
POST {{baseUrl}}/auth/login 
content-type: application/json

{
    "username": "testitest",
    "password": "test1234"
}

###

# @name getProfile
GET {{baseUrl}}/profile
Cookie: access_token=testitest

###

# @name refreshToken
## @no-cookie-jar
POST {{baseUrl}}/auth/refresh
Cookie: refresh_token=eyJhbGcIOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpdGVzdCIsInRva2VuSWQiOiIxZWUxNjAwNC04Y2FkLTQ0YTktYWRhMy1kNzJjYzMwMDYxZWQiLCJpYXQiOjE3MTI0OTk5NzIsImV4cCI6MTcxMzEwNDc3Mn0.gyepYCF59lpTCwfIbdldbKHyuaQVX8v92jVAmMUKdfw