@baseUrl = http://localhost:3000

POST {{baseUrl}}/workouts/create-exercise
content-type: application/json

{
    "name": "Bench Press"
}

###
# @name exercises
GET {{baseUrl}}/workouts/exercises

###

GET {{baseUrl}}/workouts/exercises?filter=bench

###
# @name create_workout
POST {{baseUrl}}/workouts/create-workout
content-type: application/json

{
    "name": "First Workout",
    "exercises": [
        {
            "exercise": "testitest",
            "sets": 3,
            "reps": 10
        }
    ]
}

###

GET {{baseUrl}}/workouts/workouts

###

GET {{baseUrl}}/workouts/workout/{{create_workout.response.body._id}}

###
# @name save_workout

POST {{baseUrl}}/workouts/save-workout
content-type: application/json

{
    "startTime": "2022-01-01T00:00:05Z",
    "endTime": "2022-01-01T00:00:10Z",
    "exercises": [
        {
            "exercise": "{{exercises.response.body.data.[0]._id}}",
            "sets": 3,
            "reps": 10,
            "weight": 100
        }
    ]
}

###

GET {{baseUrl}}/workouts/workout-logs?sortOrder=asc